export const INITIAL_CATEGORIES = [
   "Personal Care",
   "Alcohol",
   "Groceries",
   "Dining",
   "Fuel",
   "Shopping",
   "Entertainment",
   "Travel",
   "Health",
   "Education",
   "Utilities",
   "Rent/Mortgage",
   "Salary",
   "Investment",
   "Gift",
   "Other",
   "Home Improvement",
   "Subscriptions",
   "Insurance",
   "Taxes",
]